version: '3.8'
services:
  backend:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile.backend
    ports:
      - "8000:8000"
  dpi:
    image: jarvis-dpi:latest
    network_mode: host
